title: Loctempt's-Blog
description: "A Jekyll Blog Theme For Hackers"
author:
  name: "loctempt"
  email: "xiyue_jiang@outlook.com"
  url: "loctempt.github.io/blog_of_xiyuejiang"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 10 
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "loctempt"
year : "2019"
